name = "uithub_dashboard"
main = "main.ts"
compatibility_date = "2025-01-25"

routes = [
  { pattern = "dashboard.uithub.com", custom_domain = true }
]

[vars]
GITHUB_REDIRECT_URI = "https://dashboard.uithub.com/callback"
LOGIN_REDIRECT_URI = "/dashboard"

[[d1_databases]]
binding = "SPONSORFLARE"
database_name = "sponsorflare"
database_id = "df33c8b1-5b37-4a33-9a33-0545074f250b"
preview_database_id = "df33c8b1-5b37-4a33-9a33-0545074f250b"

[placement]
mode = "smart"
