name = "uithub_dashboard"
main = "main.ts"
compatibility_date = "2025-01-25"
dev.port = 3000

routes = [
  { pattern = "dashboard.forgithub.com", custom_domain = true }
]


assets.directory = "./public"

[vars]
GITHUB_REDIRECT_URI = "https://dashboard.forgithub.com/callback"
LOGIN_REDIRECT_URI = "/dashboard"
COOKIE_DOMAIN_SHARING = "true"

[[durable_objects.bindings]]
name = "SPONSOR_DO"
class_name = "SponsorDO"
# This allows to use the same DO even though it's defined in another worker!
script_name = "sponsorflare2"

[[durable_objects.bindings]]
name = "RATELIMIT_DO"
class_name = "RatelimitDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RatelimitDO"]
