name = "uithub_dashboard"
main = "main.ts"
compatibility_date = "2025-01-25"

routes = [
  { pattern = "dashboard.uithub.com", custom_domain = true }
]

[vars]
GITHUB_REDIRECT_URI = "https://dashboard.uithub.com/callback"
LOGIN_REDIRECT_URI = "/dashboard"

[[durable_objects.bindings]]
name = "SPONSOR_DO"
class_name = "SponsorDO"
script_name = "sponsorflare"

[[migrations]]
tag = "v1"
new_classes = ["SponsorDO"]
