name = "monoflare"
main = "main.ts"
compatibility_date = "2025-01-25"

routes = [
  { pattern = "monoflare.cloud", custom_domain = true },
  { pattern = "www.monoflare.cloud", custom_domain = true }
]

[vars]
GITHUB_REDIRECT_URI = "https://monoflare.cloud/callback"
GITHUB_SCOPE = "user:email"