name = "monoflare"
main = "main.ts"
compatibility_date = "2025-01-25"

assets = { directory = "./public"}
routes = [
  { pattern = "monoflare.cloud", custom_domain = true },
  { pattern = "www.monoflare.cloud", custom_domain = true }
]

[vars]
GITHUB_REDIRECT_URI = "https://monoflare.cloud/callback"
LOGIN_REDIRECT_URI = "/dashboard"